# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "461cf2c81050c802a8eb865615750cf1"
name = "greenlease"
handle = "greenlease"
application_url = "https://solo-harder-constitute-positive.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-682bebea.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://solo-harder-constitute-positive.trycloudflare.com/auth/callback",
  "https://solo-harder-constitute-positive.trycloudflare.com/auth/shopify/callback",
  "https://solo-harder-constitute-positive.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
